name: Deploy ppt 
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: tencent_server
    defaults:
      run:
        working-directory: ./ppt
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy pages
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "./dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}        
          
